catdad/grandma

lib/forkmaster.js, lib/run.js, package.json, test/run.test.js
=> Low duration values now error instead of running tests forever

fixtures/diff-metrics.js, lib/report.js, views/plot.html
=> add ability to use a different number custom metrics and still produce plot reports

fixtures/categories-mixed.js, lib/report.js, test/report.test.js
=> 87 categories in json report

lib/is-stream.js, package.json
=> 96 stdout hotfix

bin/cli.js, package.json
=> allowing to define a non-existent path as --out in the cli

lib/report.js, test/report.test.js
=> outputting box plots for categories

bin/cli.js, docs/api-grandma-diff.md, docs/api-grandma-report.md, docs/cli-grandma-diff.md, docs/cli-grandma-report.md, docs/readme.md, index.js, lib/argv.js, lib/report-diff.js, package.json, test/data/testdata.js, test/mocha.opts, test/report-diff.test.js, test/report.test.js
=> 103 diff stats

lib/report.js, package.json, test/report.test.js
=> plot reporter callback hotfix

.codeclimate.yml, .travis.yml, lib/run-mode-rate.js, package.json
=> updated to eslint 3

.bithoundrc
=> adding .bithoundrc

lib/report-diff.js, test/report-diff.test.js
=> preserving order in the diff reporter

test/_fixtures/record.js, test/cli/report.test.js, test/data/testexpectations.js, test/estimate-concurrent.test.js, test/estimate-duration.test.js, test/estimate-rate.test.js, test/report-diff.test.js, test/run-rate-values.test.js
=> removing some duplicate code

examples/runtime-adjustment-custom-tag.js, lib/forkmaster.js, test/run.interactive.test.js
=> Implementing #pause and #resume for the interactive API

.bithoundrc, test/_util/timeTest.js
Not sure if I need it, but I don't want it in a branch anymore.
=> fake time helper

.npmignore, .travis.yml, package.json
=> fix for the plot reporter when custom timer names are not safe to use as js variables

views/html-report/html.html, views/html-report/line-graph.js
=> adding the test name as the title to the line graph

views/html-report/html.html, views/html-report/scatter-plot.js, views/html-report/style.css
=> adding a title for the scatter plot

views/html-report/html.html, views/html-report/scatter-plot.js, views/html-report/style.css
=> cleaned up a bunch of css names

docs/api-grandma-run.md, docs/cli-grandma-run.md, lib/run-mode-concurrent.js, lib/run-mode-rate.js, lib/run.js, test/run-mode-concurrent.test.js, test/run-mode-rate.test.js, test/run.interactive.test.js
=> enabling running tests indefinitely using a duration of 0

.travis.yml
=> linting in a separate stage

lib/forkmaster.js, lib/run-mode-concurrent.js, lib/run-mode-rate.js, lib/runner.js, test/_util/timeTest.js, test/run-mode-concurrent.test.js, test/run-mode-helper.temp.js, test/run-mode-rate.test.js, test/run.interactive.test.js, test/runner.test.js
=> extracting run logic from forkmaster

package.json
=> updating to the latest duration-js

package.json
=> updating to the latest lodash

.travis.yml, appveyor.yml, lib/run-utils.js, test/run-utils.test.js
=> testing in node 10

fixtures/data.js, lib/fork.js, lib/forkmaster.js, lib/thread-utils.js, test/run.test.js
=> adding generic data bucket to test context which will be included in the test report

lib/forkmaster.js, package.json, test/_harnesses/api-run.js, test/harness.test.js
=> fixing process hanging when running a test

.gitignore, .npmignore, lib/report-html.js, lib/report-plot.js, lib/run-utils.js, package.json, test/_harnesses/api-report.js, test/data/testexpectations.js, test/harness.test.js, test/run-utils.test.js, test/run.interactive.test.js
=> handling end of all sorts of streams provided to run and report commands

.eslintrc.json, lib/fork.js, lib/forkmaster.js, lib/report-diff.js, lib/report-html.js, lib/report-json.js, lib/report-plot.js, package.json, test/_harnesses/api-report.js, test/_harnesses/api-run.js, test/cli/report.test.js, test/data/testexpectations.js, test/harness.test.js, test/report.test.js
=> using newer version of eslint

docs/test-custom-metrics.md, fixtures/metrics-numeric.js, lib/fork.js, lib/report-json.js, lib/report-serializer.js, lib/report-text.js, test/data/testdata.js, test/report.test.js, test/run.test.js
=> adding custom numeric metrics
